name: Update HubSpot Invoices

on:
  workflow_dispatch: {}
  schedule:
    - cron: "1 4 * * *"   # runs daily at 04:01 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run invoice update script
        env:
          HS: ${{ secrets.HS }}
        run: node .github/workflows/update-invoice-dates.js
